[package]
name = "rustomata"
version = "0.1.0"
authors = ["Tobias Denkinger <tobias.denkinger@tu-dresden.de>"]

[dependencies]
clap = "2.19"
num-traits = "0.1.36"
ordered-float = { git = "https://github.com/tud-fop/rust-ordered-float.git" }
nom = "^2.2"
time = "0.1.38"
rand = "0.3.16"
